# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/clock.xdc

# XDC: new/port.xdc

# Block Designs: bd/led/led.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led || ORIG_REF_NAME==led} -quiet] -quiet

# IP: bd/led/ip/led_proc_sys_reset_0_1/led_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_proc_sys_reset_0_1 || ORIG_REF_NAME==led_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/led/ip/led_processing_system7_0_0/led_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_processing_system7_0_0 || ORIG_REF_NAME==led_processing_system7_0_0} -quiet] -quiet

# IP: bd/led/ip/led_axi_interconnect_0_imp_xbar_0/led_axi_interconnect_0_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_axi_interconnect_0_imp_xbar_0 || ORIG_REF_NAME==led_axi_interconnect_0_imp_xbar_0} -quiet] -quiet

# IP: bd/led/ip/led_axi_interconnect_0_1/led_axi_interconnect_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_axi_interconnect_0_1 || ORIG_REF_NAME==led_axi_interconnect_0_1} -quiet] -quiet

# IP: bd/led/ip/led_axi_gpio_0_0/led_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_axi_gpio_0_0 || ORIG_REF_NAME==led_axi_gpio_0_0} -quiet] -quiet

# IP: bd/led/ip/led_axi_bram_ctrl_0_1/led_axi_bram_ctrl_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_axi_bram_ctrl_0_1 || ORIG_REF_NAME==led_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/led/ip/led_xlslice_0_0/led_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_xlslice_0_0 || ORIG_REF_NAME==led_xlslice_0_0} -quiet] -quiet

# IP: bd/led/ip/led_axi_bram_ctrl_0_2/led_axi_bram_ctrl_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_axi_bram_ctrl_0_2 || ORIG_REF_NAME==led_axi_bram_ctrl_0_2} -quiet] -quiet

# IP: bd/led/ip/led_util_ds_buf_0_0/led_util_ds_buf_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_util_ds_buf_0_0 || ORIG_REF_NAME==led_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/led/ip/led_util_ds_buf_1_0/led_util_ds_buf_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_util_ds_buf_1_0 || ORIG_REF_NAME==led_util_ds_buf_1_0} -quiet] -quiet

# IP: bd/led/ip/led_axis_red_pitaya_adc_0_1/led_axis_red_pitaya_adc_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_axis_red_pitaya_adc_0_1 || ORIG_REF_NAME==led_axis_red_pitaya_adc_0_1} -quiet] -quiet

# IP: bd/led/ip/led_xlslice_1_0/led_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_xlslice_1_0 || ORIG_REF_NAME==led_xlslice_1_0} -quiet] -quiet

# IP: bd/led/ip/led_adc2bram_0_0/led_adc2bram_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_adc2bram_0_0 || ORIG_REF_NAME==led_adc2bram_0_0} -quiet] -quiet

# IP: bd/led/ip/led_blk_mem_gen_0_1/led_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_blk_mem_gen_0_1 || ORIG_REF_NAME==led_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/led/ip/led_bra2bram_0_0/led_bra2bram_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_bra2bram_0_0 || ORIG_REF_NAME==led_bra2bram_0_0} -quiet] -quiet

# IP: bd/led/ip/led_xfft_0_1/led_xfft_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_xfft_0_1 || ORIG_REF_NAME==led_xfft_0_1} -quiet] -quiet

# IP: bd/led/ip/led_xlconcat_4_0/led_xlconcat_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_xlconcat_4_0 || ORIG_REF_NAME==led_xlconcat_4_0} -quiet] -quiet

# IP: bd/led/ip/led_xlconstant_5_0/led_xlconstant_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_xlconstant_5_0 || ORIG_REF_NAME==led_xlconstant_5_0} -quiet] -quiet

# IP: bd/led/ip/led_xlconstant_7_0/led_xlconstant_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_xlconstant_7_0 || ORIG_REF_NAME==led_xlconstant_7_0} -quiet] -quiet

# IP: bd/led/ip/led_xlconstant_8_0/led_xlconstant_8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_xlconstant_8_0 || ORIG_REF_NAME==led_xlconstant_8_0} -quiet] -quiet

# IP: bd/led/ip/led_c_addsub_1_0/led_c_addsub_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_c_addsub_1_0 || ORIG_REF_NAME==led_c_addsub_1_0} -quiet] -quiet

# IP: bd/led/ip/led_c_addsub_0_0/led_c_addsub_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_c_addsub_0_0 || ORIG_REF_NAME==led_c_addsub_0_0} -quiet] -quiet

# IP: bd/led/ip/led_mult_gen_0_0/led_mult_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_mult_gen_0_0 || ORIG_REF_NAME==led_mult_gen_0_0} -quiet] -quiet

# IP: bd/led/ip/led_mult_gen_1_0/led_mult_gen_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_mult_gen_1_0 || ORIG_REF_NAME==led_mult_gen_1_0} -quiet] -quiet

# IP: bd/led/ip/led_blk_mem_gen_0_2/led_blk_mem_gen_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_blk_mem_gen_0_2 || ORIG_REF_NAME==led_blk_mem_gen_0_2} -quiet] -quiet

# IP: bd/led/ip/led_outcou_0_0/led_outcou_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_outcou_0_0 || ORIG_REF_NAME==led_outcou_0_0} -quiet] -quiet

# IP: bd/led/ip/led_xlconcat_0_1/led_xlconcat_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_xlconcat_0_1 || ORIG_REF_NAME==led_xlconcat_0_1} -quiet] -quiet

# IP: bd/led/ip/led_xlconstant_0_2/led_xlconstant_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_xlconstant_0_2 || ORIG_REF_NAME==led_xlconstant_0_2} -quiet] -quiet

# IP: bd/led/ip/led_xlconstant_2_1/led_xlconstant_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_xlconstant_2_1 || ORIG_REF_NAME==led_xlconstant_2_1} -quiet] -quiet

# IP: bd/led/ip/led_xlconcat_1_1/led_xlconcat_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_xlconcat_1_1 || ORIG_REF_NAME==led_xlconcat_1_1} -quiet] -quiet

# IP: bd/led/ip/led_xlconstant_3_1/led_xlconstant_3_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_xlconstant_3_1 || ORIG_REF_NAME==led_xlconstant_3_1} -quiet] -quiet

# IP: bd/led/ip/led_blk_mem_gen_1_2/led_blk_mem_gen_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_blk_mem_gen_1_2 || ORIG_REF_NAME==led_blk_mem_gen_1_2} -quiet] -quiet

# IP: bd/led/ip/led_accumol_0_0/led_accumol_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_accumol_0_0 || ORIG_REF_NAME==led_accumol_0_0} -quiet] -quiet

# IP: bd/led/ip/led_xlslice_2_0/led_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_xlslice_2_0 || ORIG_REF_NAME==led_xlslice_2_0} -quiet] -quiet

# IP: bd/led/ip/led_xlconcat_2_0/led_xlconcat_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_xlconcat_2_0 || ORIG_REF_NAME==led_xlconcat_2_0} -quiet] -quiet

# IP: bd/led/ip/led_xlconstant_4_0/led_xlconstant_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_xlconstant_4_0 || ORIG_REF_NAME==led_xlconstant_4_0} -quiet] -quiet

# IP: bd/led/ip/led_xlslice_3_0/led_xlslice_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_xlslice_3_0 || ORIG_REF_NAME==led_xlslice_3_0} -quiet] -quiet

# IP: bd/led/ip/led_xlslice_3_1/led_xlslice_3_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_xlslice_3_1 || ORIG_REF_NAME==led_xlslice_3_1} -quiet] -quiet

# IP: bd/led/ip/led_xlslice_0_4/led_xlslice_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_xlslice_0_4 || ORIG_REF_NAME==led_xlslice_0_4} -quiet] -quiet

# IP: bd/led/ip/led_xlslice_0_5/led_xlslice_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_xlslice_0_5 || ORIG_REF_NAME==led_xlslice_0_5} -quiet] -quiet

# IP: bd/led/ip/led_blk_mem_gen_1_4/led_blk_mem_gen_1_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_blk_mem_gen_1_4 || ORIG_REF_NAME==led_blk_mem_gen_1_4} -quiet] -quiet

# IP: bd/led/ip/led_axi_interconnect_0_imp_auto_pc_1/led_axi_interconnect_0_imp_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_axi_interconnect_0_imp_auto_pc_1 || ORIG_REF_NAME==led_axi_interconnect_0_imp_auto_pc_1} -quiet] -quiet

# IP: bd/led/ip/led_axi_interconnect_0_imp_auto_pc_0/led_axi_interconnect_0_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_axi_interconnect_0_imp_auto_pc_0 || ORIG_REF_NAME==led_axi_interconnect_0_imp_auto_pc_0} -quiet] -quiet

# XDC: /home/mukund/compfft/compfft.gen/sources_1/bd/led/ip/led_proc_sys_reset_0_1/led_proc_sys_reset_0_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==led_proc_sys_reset_0_1 || ORIG_REF_NAME==led_proc_sys_reset_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/mukund/compfft/compfft.gen/sources_1/bd/led/ip/led_proc_sys_reset_0_1/led_proc_sys_reset_0_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==led_proc_sys_reset_0_1 || ORIG_REF_NAME==led_proc_sys_reset_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/mukund/compfft/compfft.gen/sources_1/bd/led/ip/led_processing_system7_0_0/led_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==led_processing_system7_0_0 || ORIG_REF_NAME==led_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/mukund/compfft/compfft.gen/sources_1/bd/led/ip/led_axi_gpio_0_0/led_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==led_axi_gpio_0_0 || ORIG_REF_NAME==led_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/mukund/compfft/compfft.gen/sources_1/bd/led/ip/led_axi_gpio_0_0/led_axi_gpio_0_0_ooc.xdc

# XDC: /home/mukund/compfft/compfft.gen/sources_1/bd/led/ip/led_axi_gpio_0_0/led_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==led_axi_gpio_0_0 || ORIG_REF_NAME==led_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/mukund/compfft/compfft.gen/sources_1/bd/led/ip/led_util_ds_buf_0_0/led_util_ds_buf_0_0_ooc.xdc

# XDC: /home/mukund/compfft/compfft.gen/sources_1/bd/led/ip/led_util_ds_buf_0_0/led_util_ds_buf_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==led_util_ds_buf_0_0 || ORIG_REF_NAME==led_util_ds_buf_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/mukund/compfft/compfft.gen/sources_1/bd/led/ip/led_util_ds_buf_1_0/led_util_ds_buf_1_0_ooc.xdc

# XDC: /home/mukund/compfft/compfft.gen/sources_1/bd/led/ip/led_util_ds_buf_1_0/led_util_ds_buf_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==led_util_ds_buf_1_0 || ORIG_REF_NAME==led_util_ds_buf_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/mukund/compfft/compfft.gen/sources_1/bd/led/ip/led_blk_mem_gen_0_1/led_blk_mem_gen_0_1_ooc.xdc

# XDC: /home/mukund/compfft/compfft.gen/sources_1/bd/led/ip/led_blk_mem_gen_0_2/led_blk_mem_gen_0_2_ooc.xdc

# XDC: /home/mukund/compfft/compfft.gen/sources_1/bd/led/ip/led_blk_mem_gen_1_2/led_blk_mem_gen_1_2_ooc.xdc

# XDC: /home/mukund/compfft/compfft.gen/sources_1/bd/led/ip/led_blk_mem_gen_1_4/led_blk_mem_gen_1_4_ooc.xdc

# XDC: /home/mukund/compfft/compfft.gen/sources_1/bd/led/ip/led_axi_interconnect_0_imp_auto_pc_1/led_axi_interconnect_0_imp_auto_pc_1_ooc.xdc

# XDC: /home/mukund/compfft/compfft.gen/sources_1/bd/led/ip/led_axi_interconnect_0_imp_auto_pc_0/led_axi_interconnect_0_imp_auto_pc_0_ooc.xdc

# XDC: /home/mukund/compfft/compfft.gen/sources_1/bd/led/led_ooc.xdc
