# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/mukund/Desktop/Git/PS_RRI/compfft/compfft.runs/synth_1/led_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 3
set_msg_config -id {HDL-1065} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/mukund/Desktop/Git/PS_RRI/compfft/compfft.cache/wt [current_project]
set_property parent.project_path /home/mukund/Desktop/Git/PS_RRI/compfft/compfft.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part redpitaya.com:redpitaya:part0:1.1 [current_project]
set_property ip_repo_paths /home/mukund/Downloads/redpitaya_guide/cores/axis_red_pitaya_adc_v1_0 [current_project]
update_ip_catalog
set_property ip_output_repo /home/mukund/Desktop/Git/PS_RRI/compfft/compfft.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  /home/mukund/Desktop/Git/PS_RRI/compfft/compfft.srcs/sources_1/new/adc2bram.v
  /home/mukund/Desktop/Git/PS_RRI/compfft/compfft.srcs/sources_1/new/bra2bram.v
  /home/mukund/Desktop/Git/PS_RRI/compfft/compfft.srcs/sources_1/new/outcount.v
  /home/mukund/Desktop/Git/PS_RRI/compfft/compfft.srcs/sources_1/new/accumol.v
  /home/mukund/Desktop/Git/PS_RRI/compfft/compfft.gen/sources_1/bd/led/hdl/led_wrapper.v
}
add_files /home/mukund/Desktop/Git/PS_RRI/compfft/compfft.srcs/sources_1/bd/led/led.bd
set_property used_in_implementation false [get_files -all /home/mukund/Desktop/Git/PS_RRI/compfft/compfft.gen/sources_1/bd/led/ip/led_proc_sys_reset_0_1/led_proc_sys_reset_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/mukund/Desktop/Git/PS_RRI/compfft/compfft.gen/sources_1/bd/led/ip/led_proc_sys_reset_0_1/led_proc_sys_reset_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/mukund/Desktop/Git/PS_RRI/compfft/compfft.gen/sources_1/bd/led/ip/led_processing_system7_0_0/led_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/mukund/Desktop/Git/PS_RRI/compfft/compfft.gen/sources_1/bd/led/ip/led_axi_gpio_0_0/led_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/mukund/Desktop/Git/PS_RRI/compfft/compfft.gen/sources_1/bd/led/ip/led_axi_gpio_0_0/led_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mukund/Desktop/Git/PS_RRI/compfft/compfft.gen/sources_1/bd/led/ip/led_axi_gpio_0_0/led_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/mukund/Desktop/Git/PS_RRI/compfft/compfft.gen/sources_1/bd/led/ip/led_util_ds_buf_0_0/led_util_ds_buf_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mukund/Desktop/Git/PS_RRI/compfft/compfft.gen/sources_1/bd/led/ip/led_util_ds_buf_0_0/led_util_ds_buf_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/mukund/Desktop/Git/PS_RRI/compfft/compfft.gen/sources_1/bd/led/ip/led_util_ds_buf_1_0/led_util_ds_buf_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mukund/Desktop/Git/PS_RRI/compfft/compfft.gen/sources_1/bd/led/ip/led_util_ds_buf_1_0/led_util_ds_buf_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/mukund/Desktop/Git/PS_RRI/compfft/compfft.gen/sources_1/bd/led/ip/led_blk_mem_gen_0_1/led_blk_mem_gen_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mukund/Desktop/Git/PS_RRI/compfft/compfft.gen/sources_1/bd/led/ip/led_blk_mem_gen_0_2/led_blk_mem_gen_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mukund/Desktop/Git/PS_RRI/compfft/compfft.gen/sources_1/bd/led/ip/led_blk_mem_gen_1_2/led_blk_mem_gen_1_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mukund/Desktop/Git/PS_RRI/compfft/compfft.gen/sources_1/bd/led/ip/led_blk_mem_gen_1_4/led_blk_mem_gen_1_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mukund/Desktop/Git/PS_RRI/compfft/compfft.gen/sources_1/bd/led/ip/led_axi_interconnect_0_imp_auto_pc_1/led_axi_interconnect_0_imp_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mukund/Desktop/Git/PS_RRI/compfft/compfft.gen/sources_1/bd/led/ip/led_axi_interconnect_0_imp_auto_pc_0/led_axi_interconnect_0_imp_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mukund/Desktop/Git/PS_RRI/compfft/compfft.gen/sources_1/bd/led/led_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/mukund/Desktop/Git/PS_RRI/compfft/compfft.srcs/constrs_1/new/clock.xdc
set_property used_in_implementation false [get_files /home/mukund/Desktop/Git/PS_RRI/compfft/compfft.srcs/constrs_1/new/clock.xdc]

read_xdc /home/mukund/Desktop/Git/PS_RRI/compfft/compfft.srcs/constrs_1/new/port.xdc
set_property used_in_implementation false [get_files /home/mukund/Desktop/Git/PS_RRI/compfft/compfft.srcs/constrs_1/new/port.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/mukund/Desktop/Git/PS_RRI/compfft/compfft.srcs/utils_1/imports/synth_1/led_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top led_wrapper -part xc7z010clg400-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef led_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file led_wrapper_utilization_synth.rpt -pb led_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
