#!/usr/bin/env bash
#**********************************************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Script generated by Vivado on Wed Jul 09 15:04:50 IST 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved. 
#
# Filename     : led.sh
# Simulator    : Cadence Xcelium Parallel Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : led.sh
#                led.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                led.sh [-reset_run]
#                led.sh [-reset_log]
#                led.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the AMD simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'led.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************

# catch pipeline exit status
set -Eeuo pipefail

# set xmvhdl compile options
xmvhdl_opts="-64bit -messages -relax -logfile .tmp_log -update"

# set xmvlog compile options
xmvlog_opts="-64bit -messages -logfile .tmp_log -update"

# set xmelab elaboration options
xmelab_opts="-64bit -relax -access +r -namemap_mixgen -messages -logfile elaborate.log"

# set xmsim simulation options
xmsim_opts="-64bit -logfile simulate.log"

# set design libraries for elaboration
design_libs_elab="-libname xilinx_vip -libname xpm -libname lib_cdc_v1_0_3 -libname proc_sys_reset_v5_0_16 -libname xil_defaultlib -libname axi_infrastructure_v1_1_0 -libname axi_vip_v1_1_19 -libname processing_system7_vip_v1_0_21 -libname generic_baseblocks_v2_1_2 -libname axi_register_slice_v2_1_33 -libname fifo_generator_v13_2_11 -libname axi_data_fifo_v2_1_32 -libname axi_crossbar_v2_1_34 -libname axi_lite_ipif_v3_0_4 -libname interrupt_control_v3_1_5 -libname axi_gpio_v2_0_35 -libname axi_bram_ctrl_v4_1_11 -libname xlslice_v1_0_4 -libname blk_mem_gen_v8_4_9 -libname xbip_utils_v3_0_14 -libname axi_utils_v2_0_10 -libname c_reg_fd_v12_0_10 -libname xbip_dsp48_wrapper_v3_0_6 -libname xbip_pipe_v3_0_10 -libname c_addsub_v12_0_19 -libname c_shift_ram_v12_0_18 -libname mult_gen_v12_0_22 -libname floating_point_v7_1_19 -libname cmpy_v6_0_25 -libname floating_point_v7_0_24 -libname xfft_v9_1_13 -libname xlconcat_v2_1_6 -libname xlconstant_v1_1_9 -libname axi_protocol_converter_v2_1_33 -libname xilinx_vip -libname unisims_ver -libname unimacro_ver -libname secureip"

# set design libraries
design_libs=(simprims_ver xilinx_vip xpm lib_cdc_v1_0_3 proc_sys_reset_v5_0_16 xil_defaultlib axi_infrastructure_v1_1_0 axi_vip_v1_1_19 processing_system7_vip_v1_0_21 generic_baseblocks_v2_1_2 axi_register_slice_v2_1_33 fifo_generator_v13_2_11 axi_data_fifo_v2_1_32 axi_crossbar_v2_1_34 axi_lite_ipif_v3_0_4 interrupt_control_v3_1_5 axi_gpio_v2_0_35 axi_bram_ctrl_v4_1_11 xlslice_v1_0_4 blk_mem_gen_v8_4_9 xbip_utils_v3_0_14 axi_utils_v2_0_10 c_reg_fd_v12_0_10 xbip_dsp48_wrapper_v3_0_6 xbip_pipe_v3_0_10 c_addsub_v12_0_19 c_shift_ram_v12_0_18 mult_gen_v12_0_22 floating_point_v7_1_19 cmpy_v6_0_25 floating_point_v7_0_24 xfft_v9_1_13 xlconcat_v2_1_6 xlconstant_v1_1_9 axi_protocol_converter_v2_1_33)

# simulation root library directory
sim_lib_dir="xcelium_lib"

# script info
echo -e "led.sh - Script generated by export_simulation (Vivado v2024.2 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./led.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  xmvlog -work xilinx_vip $xmvlog_opts -sv +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/ec67/hdl" +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/86fe/hdl" +incdir+"/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
  "/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
  "/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
  "/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
  "/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
  "/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
  "/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
  "/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
  "/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee compile.log; cat .tmp_log > xmvlog.log 2>/dev/null

  xmvlog -work xpm $xmvlog_opts -sv +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/ec67/hdl" +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/86fe/hdl" +incdir+"/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  "/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xpm -V93 $xmvhdl_opts \
  "/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > xmvhdl.log 2>/dev/null

  xmvhdl -work lib_cdc_v1_0_3 -V93 $xmvhdl_opts \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/2a4f/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work proc_sys_reset_v5_0_16 -V93 $xmvhdl_opts \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/0831/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/led/ip/led_proc_sys_reset_0_1/sim/led_proc_sys_reset_0_1.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work axi_infrastructure_v1_1_0 $xmvlog_opts +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/ec67/hdl" +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/86fe/hdl" +incdir+"/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_vip_v1_1_19 $xmvlog_opts -sv +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/ec67/hdl" +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/86fe/hdl" +incdir+"/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/8c45/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work processing_system7_vip_v1_0_21 $xmvlog_opts -sv +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/ec67/hdl" +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/86fe/hdl" +incdir+"/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/86fe/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/ec67/hdl" +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/86fe/hdl" +incdir+"/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/led/ip/led_processing_system7_0_0/sim/led_processing_system7_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work generic_baseblocks_v2_1_2 $xmvlog_opts +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/ec67/hdl" +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/86fe/hdl" +incdir+"/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/0c28/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_register_slice_v2_1_33 $xmvlog_opts +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/ec67/hdl" +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/86fe/hdl" +incdir+"/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/3ee4/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_11 $xmvlog_opts +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/ec67/hdl" +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/86fe/hdl" +incdir+"/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/6080/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work fifo_generator_v13_2_11 -V93 $xmvhdl_opts \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/6080/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_11 $xmvlog_opts +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/ec67/hdl" +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/86fe/hdl" +incdir+"/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/6080/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_data_fifo_v2_1_32 $xmvlog_opts +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/ec67/hdl" +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/86fe/hdl" +incdir+"/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/65ce/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_crossbar_v2_1_34 $xmvlog_opts +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/ec67/hdl" +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/86fe/hdl" +incdir+"/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/a7e3/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/ec67/hdl" +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/86fe/hdl" +incdir+"/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/led/ip/led_axi_interconnect_0_imp_xbar_0/sim/led_axi_interconnect_0_imp_xbar_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work axi_lite_ipif_v3_0_4 -V93 $xmvhdl_opts \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work interrupt_control_v3_1_5 -V93 $xmvhdl_opts \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/d8cc/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_gpio_v2_0_35 -V93 $xmvhdl_opts \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/6718/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/led/ip/led_axi_gpio_0_0/sim/led_axi_gpio_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_bram_ctrl_v4_1_11 -V93 $xmvhdl_opts \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/df79/hdl/axi_bram_ctrl_v4_1_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/led/ip/led_axi_bram_ctrl_0_1/sim/led_axi_bram_ctrl_0_1.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xlslice_v1_0_4 $xmvlog_opts +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/ec67/hdl" +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/86fe/hdl" +incdir+"/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/a97c/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/ec67/hdl" +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/86fe/hdl" +incdir+"/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/led/ip/led_xlslice_0_0/sim/led_xlslice_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/led/ip/led_util_ds_buf_0_0/util_ds_buf.vhd" \
  "../../../bd/led/ip/led_util_ds_buf_0_0/sim/led_util_ds_buf_0_0.vhd" \
  "../../../bd/led/ip/led_util_ds_buf_1_0/sim/led_util_ds_buf_1_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/ec67/hdl" +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/86fe/hdl" +incdir+"/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/led/ipshared/088b/axis_red_pitaya_adc.v" \
  "../../../bd/led/ip/led_axis_red_pitaya_adc_0_1/sim/led_axis_red_pitaya_adc_0_1.v" \
  "../../../bd/led/ip/led_xlslice_1_0/sim/led_xlslice_1_0.v" \
  "../../../bd/led/ip/led_adc2bram_0_0/sim/led_adc2bram_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work blk_mem_gen_v8_4_9 $xmvlog_opts +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/ec67/hdl" +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/86fe/hdl" +incdir+"/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/5ec1/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/ec67/hdl" +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/86fe/hdl" +incdir+"/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/led/ip/led_blk_mem_gen_0_1/sim/led_blk_mem_gen_0_1.v" \
  "../../../bd/led/ip/led_bra2bram_0_0/sim/led_bra2bram_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xbip_utils_v3_0_14 -V93 $xmvhdl_opts \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/b27f/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_utils_v2_0_10 -V93 $xmvhdl_opts \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7e77/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work c_reg_fd_v12_0_10 -V93 $xmvhdl_opts \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/47fd/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xbip_dsp48_wrapper_v3_0_6 -V93 $xmvhdl_opts \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/f596/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xbip_pipe_v3_0_10 -V93 $xmvhdl_opts \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/d531/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work c_addsub_v12_0_19 -V93 $xmvhdl_opts \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/a1b8/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work c_shift_ram_v12_0_18 -V93 $xmvhdl_opts \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/fe8a/hdl/c_shift_ram_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work mult_gen_v12_0_22 -V93 $xmvhdl_opts \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/e765/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work floating_point_v7_1_19 -V93 $xmvhdl_opts \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/bf3d/hdl/floating_point_v7_1_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work floating_point_v7_1_19 $xmvlog_opts +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/ec67/hdl" +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/86fe/hdl" +incdir+"/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/bf3d/hdl/floating_point_v7_1_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work cmpy_v6_0_25 $xmvlog_opts +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/ec67/hdl" +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/86fe/hdl" +incdir+"/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/01d8/hdl/cmpy_v6_0_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work cmpy_v6_0_25 -V93 $xmvhdl_opts \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/01d8/hdl/cmpy_v6_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work floating_point_v7_0_24 -V93 $xmvhdl_opts \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/f38a/hdl/floating_point_v7_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xfft_v9_1_13 -V200X $xmvhdl_opts \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/float_pkg.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/cfloat_pkg.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/DELAY.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/CDELAY.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/BDELAY.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/DS.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/CB.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/DSN.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/DSPFP32_GW.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/InputSwap.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/PARFFT2.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/PARFFT4.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/PARFFT.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/R2BUTTERFLY.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/R2TableFP32_pkg.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/R2TableFP32.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/R4BUTTERFLY.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/R4TableFP32_pkg.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/R4TableFP32.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/STAGE.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/SystolicFFT.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/xfft_v9_1_core_ssr.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xfft_v9_1_13 -V93 $xmvhdl_opts \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/xfft_v9_1_viv_comp.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/xfft_v9_1_comp.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/pkg.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/half_sincos_tw_table.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/quarter_sin_tw_table.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/quarter2_sin_tw_table.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/adder.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/adder_bypass.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/logic_gate.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/equ_rtl.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/cnt_sat.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/cnt_tc_rtl.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/cnt_tc_rtl_a.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/cnt_tc_rtl_b.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/shift_ram.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/srl_fifo.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/mux_bus2.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/mux_bus4.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/mux_bus8.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/mux_bus16.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/mux_bus32.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/dist_mem.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/dpm.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/dpm_hybrid.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/reg_rs_rtl.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/sub_byp.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/sub_byp_j.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/subtracter.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/xor_bit_gate.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/arith_shift1.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/arith_shift3.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/butterfly_dsp48e.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/butterfly_dsp48e_hybrid.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/butterfly_dsp48e_bypass.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/butterfly_dsp48e_bypass_hybrid.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/butterfly_dsp48e_mul_j_bypass.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/butterfly_dsp48e_mul_j_bypass_hybrid.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/butterfly_dsp48e_simd.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/butterfly_dsp48e_simd_bypass.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/butterfly_dsp48e_simd_mul_j_bypass.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/bf_dsp.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/bf_dsp_bypass.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/bf_dsp_mul_j_bypass.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/bfly_byp.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/bfly_byp_j.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/butterfly.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/twos_comp.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/cmpy.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/dfly_byp.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/dragonfly_dsp48_bypass.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/so_xk_counter.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/flow_control_b.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/flow_control_c.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/max2_2.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/in_ranger.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/in_switch4.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/out_addr_gen_b.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/out_switch4.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/overflow_gen.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/unbiased_round.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/pe4.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/r2_in_addr.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/r2_ovflo_gen.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/r2_pe.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/range_r2.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/r2_ranger.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/r2_rw_addr.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/r2_tw_addr.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/twgen_distmem.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/twgen_distmem_so.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/twgen_half_sincos.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/twgen_quarter_sin.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/twiddle_gen.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/r2_control.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/scale_logic.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/r2_datapath.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/rw_addr_gen_b.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/tw_gen_p2.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/tw_gen_p4.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/tw_addr_gen.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/r4_control.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/range_r4.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/r4_ranger.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/r4_datapath.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/r22_twos_comp_mux.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/r22_delay_mux.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/r22_srl_memory.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/r22_memory.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/r22_bfly_byp.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/r22_bf.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/r22_bf_sp.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/r22_cnt_ctrl.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/r22_flow_ctrl.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/r22_ovflo.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/r22_busy.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/r22_tw_gen.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/r22_pe.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/r22_right_shift.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/r22_shift_decode.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/r22_var_unbiased_round.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/so_n_counter.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/so_io_addr_gen.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/so_run_addr_gen_rotator.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/so_run_addr_gen_left_shift.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/so_run_addr_gen.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/so_addr_gen.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/so_control_fsm.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/so_control.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/so_memory.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/so_ranger.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/so_datapath.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/pipe_blank.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/fp_get_block_max_exp.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/fp_convert_to_block_fp.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/fp_convert_to_fp.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/fp_shift_ram_clr_op.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/xfft_v9_1_axi_pkg.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/axi_wrapper_input_fifo.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/axi_wrapper_output_fifo.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/axi_wrapper.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/xfft_v9_1_b.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/xfft_v9_1_c.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/xfft_v9_1_d.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/xfft_v9_1_e.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/xfft_v9_1_fp.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/xfft_v9_1_core.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/xfft_v9_1_viv.vhd" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/7162/hdl/xfft_v9_1.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/led/ip/led_xfft_0_1/sim/led_xfft_0_1.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xlconcat_v2_1_6 $xmvlog_opts +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/ec67/hdl" +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/86fe/hdl" +incdir+"/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/6120/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/ec67/hdl" +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/86fe/hdl" +incdir+"/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/led/ip/led_xlconcat_4_0/sim/led_xlconcat_4_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xlconstant_v1_1_9 $xmvlog_opts +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/ec67/hdl" +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/86fe/hdl" +incdir+"/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/e2d2/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/ec67/hdl" +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/86fe/hdl" +incdir+"/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/led/ip/led_xlconstant_5_0/sim/led_xlconstant_5_0.v" \
  "../../../bd/led/ip/led_xlconstant_7_0/sim/led_xlconstant_7_0.v" \
  "../../../bd/led/ip/led_xlconstant_8_0/sim/led_xlconstant_8_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/led/ip/led_c_addsub_1_0/sim/led_c_addsub_1_0.vhd" \
  "../../../bd/led/ip/led_c_addsub_0_0/sim/led_c_addsub_0_0.vhd" \
  "../../../bd/led/ip/led_mult_gen_0_0/sim/led_mult_gen_0_0.vhd" \
  "../../../bd/led/ip/led_mult_gen_1_0/sim/led_mult_gen_1_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/ec67/hdl" +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/86fe/hdl" +incdir+"/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/led/ip/led_xlconstant_0_1/sim/led_xlconstant_0_1.v" \
  "../../../bd/led/ip/led_xlslice_3_0/sim/led_xlslice_3_0.v" \
  "../../../bd/led/ip/led_xlslice_4_0/sim/led_xlslice_4_0.v" \
  "../../../bd/led/ip/led_blk_mem_gen_0_2/sim/led_blk_mem_gen_0_2.v" \
  "../../../bd/led/ip/led_outcou_0_0/sim/led_outcou_0_0.v" \
  "../../../bd/led/ip/led_xlconcat_0_1/sim/led_xlconcat_0_1.v" \
  "../../../bd/led/ip/led_xlconstant_0_2/sim/led_xlconstant_0_2.v" \
  "../../../bd/led/ip/led_xlconstant_1_2/sim/led_xlconstant_1_2.v" \
  "../../../bd/led/ip/led_xlconstant_2_1/sim/led_xlconstant_2_1.v" \
  "../../../bd/led/ip/led_xlconcat_1_1/sim/led_xlconcat_1_1.v" \
  "../../../bd/led/ip/led_xlconstant_3_1/sim/led_xlconstant_3_1.v" \
  "../../../bd/led/ip/led_blk_mem_gen_1_2/sim/led_blk_mem_gen_1_2.v" \
  "../../../bd/led/ip/led_blk_mem_gen_1_3/sim/led_blk_mem_gen_1_3.v" \
  "../../../bd/led/ip/led_xlslice_0_2/sim/led_xlslice_0_2.v" \
  "../../../bd/led/ip/led_xlslice_0_3/sim/led_xlslice_0_3.v" \
  "../../../bd/led/ip/led_accumol_0_0/sim/led_accumol_0_0.v" \
  "../../../bd/led/sim/led.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_protocol_converter_v2_1_33 $xmvlog_opts +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/ec67/hdl" +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/86fe/hdl" +incdir+"/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../compfft.gen/sources_1/bd/led/ipshared/27ae/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/ec67/hdl" +incdir+"../../../../compfft.gen/sources_1/bd/led/ipshared/86fe/hdl" +incdir+"/home/mukund/Desktop/ToolsXilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/led/ip/led_axi_interconnect_0_imp_auto_pc_1/sim/led_axi_interconnect_0_imp_auto_pc_1.v" \
  "../../../bd/led/ip/led_axi_interconnect_0_imp_auto_pc_0/sim/led_axi_interconnect_0_imp_auto_pc_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  xmelab $xmelab_opts $design_libs_elab xil_defaultlib.led xil_defaultlib.glbl
}

# RUN_STEP: <simulate>
simulate()
{
  xmsim $xmsim_opts xil_defaultlib.led -input simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

 # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="hdl.var"
  touch $file

  file="cds.lib"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($lib_map_path == "") ]]; then
    lib_map_path="/home/mukund/compfft/compfft.cache/compile_simlib/xcelium"
  fi

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="INCLUDE $lib_map_path/cds.lib"
    echo $incl_ref >> $file
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="DEFINE $lib $sim_lib_dir/$lib"
    echo $mapping >> $file
  done
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log led_sc.so .tmp_log xcelium_lib waves.shm c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./led.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -reset_run)     b_reset_run=1     ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: led.sh [-help]\n\
Usage: led.sh [-step]\n\
Usage: led.sh [-lib_map_path]\n\
Usage: led.sh [-reset_run]\n\
Usage: led.sh [-reset_log]\n\
Usage: led.sh [-keep_index]\n\
Usage: led.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_reset_run=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
